### ISSUE TITLE
CI 구축하기

### ISSUE THREAD

**Issue by Cho-SangHyun** [SWmaestro-14th-somsatang/wooyoungsoo-FE#9]
## Description
- CI 구축하기

## Todo
- [x] main브랜치에 푸쉬될 때 테스트, 빌드를 자동으로 진행하게 하려고 함
- [x] GitHub Action으로 만들 예정

**Comment by Cho-SangHyun** [comment]
```
name: Flutter CI (test & build)

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
    
jobs:
  Tests-and-build-ubuntu-and-window:
    name: Tests and Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk
      - run: flutter build appbundle

  Tests-and-build-macos:
    name: Tests and Build on MacOS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.10.0'
        channel: 'stable'
        architecture: x64
    - run: flutter pub get
    - run: flutter test
    - run: flutter build ios --release --no-codesign
```

다음과 같이 작성하여 만듦.
